// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEvidence(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddEvidence'](arg1, arg2, arg3);
}

export function GenerateReport() {
  return window['go']['main']['App']['GenerateReport']();
}

export function GetCalls(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetCalls'](arg1, arg2, arg3, arg4);
}

export function GetChatMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetChatMessages'](arg1, arg2, arg3);
}

export function GetChats(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetChats'](arg1, arg2, arg3);
}

export function GetContacts(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetContacts'](arg1, arg2, arg3);
}

export function GetEvidence() {
  return window['go']['main']['App']['GetEvidence']();
}

export function GetExtractionInfo() {
  return window['go']['main']['App']['GetExtractionInfo']();
}

export function GetFileHex(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFileHex'](arg1, arg2, arg3);
}

export function GetFileText(arg1, arg2) {
  return window['go']['main']['App']['GetFileText'](arg1, arg2);
}

export function GetFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetFiles'](arg1, arg2, arg3, arg4);
}

export function GetLocations(arg1, arg2) {
  return window['go']['main']['App']['GetLocations'](arg1, arg2);
}

export function GetParseStatus() {
  return window['go']['main']['App']['GetParseStatus']();
}

export function GetSqliteData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetSqliteData'](arg1, arg2, arg3, arg4);
}

export function GetSqliteTables(arg1) {
  return window['go']['main']['App']['GetSqliteTables'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTimeline(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTimeline'](arg1, arg2, arg3, arg4);
}

export function OpenUfdr(arg1) {
  return window['go']['main']['App']['OpenUfdr'](arg1);
}

export function RemoveEvidence(arg1, arg2) {
  return window['go']['main']['App']['RemoveEvidence'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
