// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddEvidence(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetCalls(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<main.Call>>;

export function GetChatMessages(arg1:string,arg2:number,arg3:number):Promise<Array<main.Message>>;

export function GetChats():Promise<Array<main.Chat>>;

export function GetContacts(arg1:string):Promise<Array<main.Contact>>;

export function GetEvidence():Promise<Array<main.Evidence>>;

export function GetExtractionInfo():Promise<Record<string, any>>;

export function GetFiles(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<main.File>>;

export function GetLocations():Promise<Array<main.Location>>;

export function GetParseStatus():Promise<main.ParseStatus>;

export function GetSqliteData(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Record<string, any>>;

export function GetSqliteTables(arg1:string):Promise<Record<string, any>>;

export function GetStats():Promise<main.Stats>;

export function GetTimeline(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<main.TimelineEvent>>;

export function OpenUfdr(arg1:string):Promise<Record<string, string>>;

export function RemoveEvidence(arg1:string,arg2:string):Promise<void>;

export function SelectFile():Promise<string>;
